' ===================================================================
' PDF Compact launcher (silent / hidden window)
'   - Double-click to launch
'   - Silently checks GitHub for latest version, downloads if newer
'   - Opens pdf_compact_bundle.html in default browser
'   - No black command window, runs completely in background
' ===================================================================
Option Explicit

Dim sh, fso, currentDir, bundlePath, psCmd
Set sh  = CreateObject("WScript.Shell")
Set fso = CreateObject("Scripting.FileSystemObject")

' Resolve folder of this .vbs file
currentDir = fso.GetParentFolderName(WScript.ScriptFullName)
bundlePath = currentDir & "\pdf_compact_bundle.html"
sh.CurrentDirectory = currentDir

' PowerShell update-check + download (base64 encoded, hidden window)
psCmd = "powershell -NoProfile -ExecutionPolicy Bypass -WindowStyle Hidden -EncodedCommand " & _
  "JABFAHIAcgBvAHIAQQBjAHQAaQBvAG4AUAByAGUAZgBlAHIAZQBuAGMAZQA9ACcAUwBpAGwAZQBuAHQAbAB5AEMAbwBuAHQAaQBuAHUAZQAnADsAVwByAGkAdABlAC0ASABvAHMAdAAgACcAWwBQAEQARgAgAEMAbwBtAHAAYQBjAHQAXQAgAGMAaABlAGMAawBpAG4AZwAgAHUAcABkAGEAdABlAC4ALgAuACcAOwAkAGIAYQBzAGUAPQBbAFQAZQB4AHQALgBFAG4AYwBvAGQAaQBuAGcAXQA6ADoAVQBUAEYAOAAuAEcAZQB0AFMAdAByAGkAbgBnACgAWwBDAG8AbgB2AGUAcgB0AF0AOgA6AEYAcgBvAG0AQgBhAHMAZQA2ADQAUwB0AHIAaQBuAGcAKAAnAGEASABSADAAYwBIAE0ANgBMAHkAOQB5AFkAWABjAHUAWgAyAGwAMABhAEgAVgBpAGQAWABOAGwAYwBtAE4AdgBiAG4AUgBsAGIAbgBRAHUAWQAyADkAdABMADMATgBGAFEAVgBKAEQAUwBHAE4AUABUAFYAQQB2AFUARwBSAG0AUQAyADkAdABjAEcARgBqAGQAQwA5AHQAWQBXAGwAdQBMAHcAPQA9ACcAKQApADsAdAByAHkAewAkAG0APQBJAG4AdgBvAGsAZQAtAFcAZQBiAFIAZQBxAHUAZQBzAHQAIAAtAFUAcgBpACAAKAAkAGIAYQBzAGUAKwAnAHYAZQByAHMAaQBvAG4ALgBqAHMAbwBuACcAKQAgAC0AVQBzAGUAQgBhAHMAaQBjAFAAYQByAHMAaQBuAGcAIAAtAFQAaQBtAGUAbwB1AHQAUwBlAGMAIAA1ACAAfAAgAEMAbwBuAHYAZQByAHQARgByAG8AbQAtAEoAcwBvAG4AOwAkAGwAdgA9ACcAMAAuADAALgAwACcAOwBpAGYAKABUAGUAcwB0AC0AUABhAHQAaAAgACcAcABkAGYAXwBjAG8AbQBwAGEAYwB0AF8AYgB1AG4AZABsAGUALgBoAHQAbQBsACcAKQB7ACQAYwA9AEcAZQB0AC0AQwBvAG4AdABlAG4AdAAgACcAcABkAGYAXwBjAG8AbQBwAGEAYwB0AF8AYgB1AG4AZABsAGUALgBoAHQAbQBsACcAIAAtAFIAYQB3ACAALQBFAG4AYwBvAGQAaQBuAGcAIABVAFQARgA4ADsAaQBmACgAJABjACAALQBtAGEAdABjAGgAIAAiAGMAbwBuAHMAdAAgAEEAUABQAF8AVgBFAFIAUwBJAE8ATgAgAD0AIAAnACgAXABkACsAXAAuAFwAZAArAFwALgBcAGQAKwApACcAIgApAHsAJABsAHYAPQAkAE0AYQB0AGMAaABlAHMAWwAxAF0AfQB9ADsAaQBmACgAWwB2AGUAcgBzAGkAbwBuAF0AJABtAC4AdgBlAHIAcwBpAG8AbgAgAC0AZwB0ACAAWwB2AGUAcgBzAGkAbwBuAF0AJABsAHYAKQB7AFcAcgBpAHQAZQAtAEgAbwBzAHQAIAAoACIAWwBQAEQARgAgAEMAbwBtAHAAYQBjAHQAXQAgAHUAcABkAGEAdABpAG4AZwAgACQAbAB2ACAALQA+ACAAIgAgACsAIAAkAG0ALgB2AGUAcgBzAGkAbwBuACkAOwBJAG4AdgBvAGsAZQAtAFcAZQBiAFIAZQBxAHUAZQBzAHQAIAAtAFUAcgBpACAAKAAkAGIAYQBzAGUAKwAkAG0ALgBkAG8AdwBuAGwAbwBhAGQAXwBwAGEAdABoACkAIAAtAE8AdQB0AEYAaQBsAGUAIAAnAHAAZABmAF8AYwBvAG0AcABhAGMAdABfAGIAdQBuAGQAbABlAC4AaAB0AG0AbAAuAG4AZQB3ACcAIAAtAFUAcwBlAEIAYQBzAGkAYwBQAGEAcgBzAGkAbgBnACAALQBUAGkAbQBlAG8AdQB0AFMAZQBjACAANgAwADsAaQBmACgAVABlAHMAdAAtAFAAYQB0AGgAIAAnAHAAZABmAF8AYwBvAG0AcABhAGMAdABfAGIAdQBuAGQAbABlAC4AaAB0AG0AbAAnACkAewBSAGUAbQBvAHYAZQAtAEkAdABlAG0AIAAnAHAAZABmAF8AYwBvAG0AcABhAGMAdABfAGIAdQBuAGQAbABlAC4AaAB0AG0AbAAnACAALQBGAG8AcgBjAGUAfQA7AFIAZQBuAGEAbQBlAC0ASQB0AGUAbQAgACcAcABkAGYAXwBjAG8AbQBwAGEAYwB0AF8AYgB1AG4AZABsAGUALgBoAHQAbQBsAC4AbgBlAHcAJwAgACcAcABkAGYAXwBjAG8AbQBwAGEAYwB0AF8AYgB1AG4AZABsAGUALgBoAHQAbQBsACcAOwBXAHIAaQB0AGUALQBIAG8AcwB0ACAAJwBbAFAARABGACAAQwBvAG0AcABhAGMAdABdACAAdQBwAGQAYQB0AGUAZAAuACcAfQBlAGwAcwBlAHsAVwByAGkAdABlAC0ASABvAHMAdAAgACIAWwBQAEQARgAgAEMAbwBtAHAAYQBjAHQAXQAgAHUAcAAgAHQAbwAgAGQAYQB0AGUAIAAoAHYAJABsAHYAKQAuACIAfQB9AGMAYQB0AGMAaAB7AFcAcgBpAHQAZQAtAEgAbwBzAHQAIAAoACIAWwBQAEQARgAgAEMAbwBtAHAAYQBjAHQAXQAgAHUAcABkAGEAdABlACAAcwBrAGkAcABwAGUAZAA6ACAAIgAgACsAIAAkAF8ALgBFAHgAYwBlAHAAdABpAG8AbgAuAE0AZQBzAHMAYQBnAGUAKQB9AA=="

' Run PowerShell hidden, wait until update finishes (0 = SW_HIDE, True = wait)
sh.Run psCmd, 0, True

' Open the (now updated) bundle in default browser
If fso.FileExists(bundlePath) Then
  sh.Run """" & bundlePath & """", 1, False
Else
  ' First-run failure: bundle didn't download (offline?)
  MsgBox "Download failed. Please check internet connection and try again.", _
         vbExclamation, "PDF Compact"
End If
